name: macOS version

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: macos-26
    steps:
      - name: plist
        run: |
          cat /System/Library/CoreServices/SystemVersion.plist
      - name: version
        run: |
          set -x
          sysctl kern.osproductversion
          sysctl kern.osrelease
          uname -a
