name: On comment

on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  try-run:
    if: |
      github.event.issue.pull_request && startsWith(github.event.comment.body, '/try')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: write
    steps:
      - run: |
          echo "$GITHUB"
        env:
          GITHUB: ${{ toJSON(github) }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
          filter: blob:none
          fetch-depth: 0
      - name: Start full CI run on comment
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          PR_TITLE: ${{ github.event.issue.title }}
          ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ github.token }}
        run: |
          set -x

          permission=$(gh api /repos/fnordig/test-repo/collaborators/${ACTOR}/permission | jq -r .permission)
          if [[ "$permission" = "admin" ]]; then
            true
          else
            echo "Insufficient permission. Stopping."
            exit 0
          fi

          pr_info=$(gh api "/repos/fnordig/test-repo/pulls/${PR_NUMBER}")
          pr_state=$(echo "$pr_info" | jq -r .state)
          if [[ "$pr_state" != "open" ]]; then
            echo "PR is not open. State: ${pr_state}. Stopping."
            exit 0
          fi

          pr_branch=$(echo "$pr_info" | jq -r .head.ref)
          echo "$pr_branch"

          workflow_id=$(gh run list --workflow=test.yml -b "$pr_branch" --json databaseId -q '.[0].databaseId')
          echo "$workflow_id"

          if echo "$PR_TITLE" | grep -q '\[full ci\]'; then
            true
          else
            new_title="[full ci] $PR_TITLE"
              gh pr edit 38 --title "$new_title"
          fi

          gh run rerun "$workflow_id"

          url="https://github.com/fnordig/test-repo/actions/runs/${workflow_id}"
          msg="Full CI run started. URL: ${url}"
          echo "$msg"
          gh pr comment "$PR_NUMBER" --body "$msg"
