# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

# This workflow periodically calls the fog-update-bot action to update
# the list of FOG metrics.yaml and ping.yaml files from its metrics_index.py


name: "Update FOG"

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  main:
    name: "Update FOG"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Setup Python
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

    - name: "Update FOG"
      id: fog-updater
      if: github.repository == 'badboy/test-repo'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ./fog-updater
        uv run fog-updater
