# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

# This workflow periodically calls the fog-update-bot action to update
# the list of FOG metrics.yaml and ping.yaml files from its metrics_index.py


name: "Update FOG"

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  main:
    name: "Update FOG"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Setup Python
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

    - name: "Update FOG"
      id: fog-updater
      if: github.repository == 'badboy/test-repo'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        uv run --project fog-updater fog-updater

    - name: "Approve workflow run for updater"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        WORKFLOW_RUNS=$(gh api 'repos/badboy/test-repo/actions/runs?branch=fog-update/update-metrics-index-main&status=action_required')
        echo "$WORKFLOW_RUNS" | jq .


        TOTAL_COUNT=$(echo "$WORKFLOW_RUNS" | jq '.total_count')
        if [[ "$TOTAL_COUNT" -eq 1 ]]; then
          echo "Workflows awaiting approval: $TOTAL_COUNT"
          exit 1
        fi

        RUN=$(echo "$WORKFLOW_RUNS" | jq '.workflow_runs[0]')
        NAME=$(echo "$RUN" | jq '.name')
        RUN_ID=$(echo "$RUN" | jq '.id')

        if [[ "$RUN_NAME" != "build-test-deploy" ]]; then
          echo "Wrong workflow waiting: $RUN_NAME"
          exit 1
        fi

        gh api --method POST "repos/badboy/test-repo/actions/runs/${RUN_ID}/approve"
